version: '3.9'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app
    restart: always
    ports:
      - 8000:8000
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - default
    volumes:
      - /root/redis/data:/data
    command:
      - --requirepass ${REDIS_PASS}

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
